<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students [
    <!ELEMENT students (student*)>
    <!ELEMENT student (roll,name,per,college)>
    <!ELEMENT roll (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT per (#PCDATA)>
    <!ELEMENT college (#PCDATA)>
    <!ENTITY iccs "INdira college of comm and science">
]>

<students>
    <student>
        <roll>15</roll>
        <name>Aryaman</name>
        <per>98.9</per>
        <college>&iccs;</college>
    </student>
    <student>
        <roll>11</roll>
        <name>kamat</name>
        <per>91.9</per>
        <college>&iccs;</college>
    </student>
</students>